[uwsgi]
;http = 0.0.0.0:8844
socket = 127.0.0.1:8844

base = /app
chdir = %(base)
home = %(base)/venv

pidfile = %(base)/pa234.pid

wsgi-file = pa234/main.py
callable = app

processes = 2
threads = 4
enable-threads = true
close-on-exec = false

vacuum = true
die-on-term = true

master = true
thunder-lock = true

harakiri = 120
need-app = true
logto = /var/log/pa234-2026/pa234.log